/**
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

public class Problem002 {

	public static void main(String[] args) {
		int x = 1;
		int y = 1;
		int next = 0;
		int sum = 0;
		while (x < 4000000) {
			if (x % 2 == 0) {
				sum += x;
			}
			next = x + y;
			x = y;
			y = next;
		}
		System.out.println(sum);

	}
}
